/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ManejadorBuscarReserva;
import java.awt.event.MouseListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author msi
 * aqui es donde el usario busca el hotel que quiere con filtros de busqueda o nombre de reserva
 */
public class FRM_BuscarReserva extends javax.swing.JFrame {

    /**
     * Creates new form FRM_BuscarReserva
     */

    public FRM_BuscarReserva() {
        initComponents();

    }
    
    
    public void  escucharBotones(ManejadorBuscarReserva manejador){
        jBSalir.addActionListener(manejador);
    }
    
    //Metodo para Llenar la tabla:
    public void setDataTable(String[][] datos, String[] encabezado)
    {
        this.jTBReservacionesDisponibles.setModel(new DefaultTableModel(datos, encabezado));
        this.jScrollPane1.setViewportView(this.jTBReservacionesDisponibles); //Cargar la Tabla y se vea la barra de Desplazamiento.
    }//Fin Metodo
    
    //Devuelva Titulo de lo seleccionado (Llenar espacios)
    public String[] getDataRow() {
        String[] datosCancion = new String[this.jTBReservacionesDisponibles.getColumnCount()];
        int filaSeleccionada = this.jTBReservacionesDisponibles.getSelectedRow();
        
        for(int i = 0; i < datosCancion.length; i++) {
            datosCancion[i] = this.jTBReservacionesDisponibles.getValueAt(filaSeleccionada, i).toString();
        }//Fin FOR
        return datosCancion;
    }//Fin Metodo DataRow
    
    //Escuchar tabla cuando se seleccione
    public void escucharMouse(MouseListener manejador) {
        this.jTBReservacionesDisponibles.addMouseListener(manejador);
    }//Fin Metodo escuchar Mouse


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTBReservacionesDisponibles = new javax.swing.JTable();
        jTFLugar = new javax.swing.JTextField();
        jBSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTBReservacionesDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Provincia", "Precio por Noche"
            }
        ));
        jScrollPane1.setViewportView(jTBReservacionesDisponibles);

        jBSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jTFLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSalir)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBSalir)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBReservacionesDisponibles;
    private javax.swing.JTextField jTFLugar;
    // End of variables declaration//GEN-END:variables
}
