/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author msi
 * aqui se le muestra al usuario las caracteristicas del hotel, y se muestra para poder marcar que servicios quiere
 * y se le pregunta por que dia quiere ingresar y cual quiere salir
 */
public class FRM_Reservar extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Reservar
     */
    public FRM_Reservar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBTNSalirR = new javax.swing.JButton();
        jLUbicacion = new javax.swing.JLabel();
        jLCapacidadMaxima = new javax.swing.JLabel();
        jBTNReservar = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLBanos = new javax.swing.JLabel();
        jLProvincia = new javax.swing.JLabel();
        jLHabitaciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBTNSalirR.setBackground(new java.awt.Color(153, 255, 204));
        jBTNSalirR.setText("Salir");

        jLUbicacion.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLUbicacion.setText("Ubicación");

        jLCapacidadMaxima.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLCapacidadMaxima.setText("Capacidad Máxima");

        jBTNReservar.setBackground(new java.awt.Color(153, 255, 204));
        jBTNReservar.setText("Reservar");

        jLNombre.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLNombre.setText("Nombre");

        jLTipo.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLTipo.setText("Tipo");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Cantidades:");

        jLBanos.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLBanos.setText("Baños");

        jLProvincia.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLProvincia.setText("Provincia");

        jLHabitaciones.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLHabitaciones.setText("Habitaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombre)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLTipo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLBanos)
                                    .addComponent(jLHabitaciones)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLCapacidadMaxima)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLProvincia)
                    .addComponent(jLUbicacion))
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jBTNReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jBTNSalirR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jLProvincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipo)
                    .addComponent(jLUbicacion))
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLBanos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLHabitaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCapacidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTNReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTNSalirR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTNReservar;
    private javax.swing.JButton jBTNSalirR;
    private javax.swing.JLabel jLBanos;
    private javax.swing.JLabel jLCapacidadMaxima;
    private javax.swing.JLabel jLHabitaciones;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLProvincia;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLUbicacion;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
